import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import OutageReport from '../models/OutageReport.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/noc-alerts';

async function checkOutageReports() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB\n');

    const reports = await OutageReport.find({}).sort({ occurrenceTime: -1 }).limit(10);
    
    console.log(`📊 Found ${reports.length} outage reports:\n`);
    
    if (reports.length === 0) {
      console.log('📭 No outage reports found. Reports will be generated by the hourly scheduler.');
    } else {
      reports.forEach((report, index) => {
        console.log(`${index + 1}. Site: ${report.siteNo} - ${report.siteCode}`);
        console.log(`   Region: ${report.region}`);
        console.log(`   Supervisor: ${report.supervisor}`);
        console.log(`   Alarm Type: ${report.alarmType}`);
        console.log(`   Status: ${report.status}`);
        console.log(`   Occurrence: ${report.occurrenceTime.toLocaleString()}`);
        console.log('');
      });
    }

    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
    
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

checkOutageReports();
